### ISSUE TITLE
Появится ли версия SOVA на Tensorflow с  DirectML ?

### ISSUE THREAD

**Issue by pin240** [sovaai/sova-tts#10]
Здравствуйте. Спасибо за ваш труд. 
У меня есть 3 видеокарты **AMD (2шт - R9 Nano и Vega64)** и **большой** дата сет на 19Гб. 
Я готов даже его отдать на общее пользование. 
Как я понял для обучения нужно видеокарта с CUDA, но у меня ее нет. Много рылся в интернете и нарвался на статью
 https://docs.microsoft.com/en-us/windows/ai/directml/gpu-tensorflow-windows .
 Понимаю что сейчас основано на Tacotron2 и увы для AMD там путь закрыт :(
 Хотелось узнать появится ли версия SOVA на Tensorflow с  DirectML для Win10 ?  Это бы открыло дорогу почти для любого GPU
 https://github.com/microsoft/tensorflow-directml
 есть вариант для pyTorch ubuntu 18
 https://www.amd.com/en/technologies/infinity-hub/pytorch

**Comment by Dekakhrone** [comment]
Здравствуйте @pin240! К сожалению, у меня, как у главного разработчика SOVA TTS, дикая неприязнь к tensorflow, так что связки Tensorflow + DirectML (по крайней мере пока) не будет, а вот обучение через указанный вами докер рассмотрим. Я надеюсь, что где-то в ноябре мы выложим новую версию с расширенным функционалом и более удобным инференсом, и если будем успевать по времени, то протестируем этот образ.
