### ISSUE TITLE
Can not run the model on inference.

### ISSUE THREAD

**Issue by vectozavr** [sovaai/sova-tts#2]
I don't have any experience with docker and maybe I do something wrong, but I can't run SOVA-TTS on my computer. (MacBook Pro 16 - 2020, MacOS BigSur 11.0.1 (20B50), Core i9, Radeon Pro 5500M 8 ГБ, 16 ГБ 2667 MHz DDR4)
I followed all steps in README file and every step worked just fine without any issues, but when I tried:

curl --request POST 'http://localhost:8899/synthesize/' --form 'voice=Natasha' --form 'text="Добрый день!"'

Model did not show any results (my computer started to compute something but without any results)

After that I tried to run this on Ubuntu-20.04.1-desktop-amd64 (using Parallels Desktop 16) and met the same issue: after I write testing string nothing happens:

![image](https://user-images.githubusercontent.com/60608292/101127490-44785900-3630-11eb-8e2c-9bc2bd567ac1.png)

**Comment by vectozavr** [comment]
I don't know why but this problem was solved after rebooting Ubuntu and retrying running several times. For Ubuntu this issue can be closed, but I still can't run on macOs.

**Comment by Dekakhrone** [comment]
@vectozavr hello! First of all, which version of the SOVA-TTS do you use: GPU or CPU?

We support only NVIDIA graphics cards at the moment (and it's our fault that we didn't clarify in the readme). 

If you are using the CPU version, then without logs it is difficult to tell what is wrong. Let's get them: while running the command above launch another terminal window and write `docker logs -f sova-tts`

**Comment by Dekakhrone** [comment]
Closed due to inactivity

**Comment by sskorol** [comment]
@Dekakhrone hi, I faced the same issue. I'm trying to run this service on Jetson Xavier NX. I've built a custom image. The container has successfully started, but in logs, I see just infinite worker booting attempts:
```
[2021-03-27 22:30:45 +0000] [1292] [INFO] Booting worker with pid: 1292
[2021-03-27 22:30:46 +0000] [1294] [INFO] Booting worker with pid: 1294
[2021-03-27 22:30:47 +0000] [1296] [INFO] Booting worker with pid: 1296
[2021-03-27 22:30:48 +0000] [1298] [INFO] Booting worker with pid: 1298
[2021-03-27 22:30:48 +0000] [1300] [INFO] Booting worker with pid: 1300
```
Here's my modified Dockerfile.gpu. I've changed only a base image that has all the ML stuff installed + added some missing deps.
```
FROM nvcr.io/nvidia/l4t-ml:r32.5.0-py3

RUN apt-get update && apt-get dist-upgrade -y && apt-get install -y --fix-missing --no-install-recommends \
    libfreetype6-dev \
    apt-utils \
    ffmpeg \
    git \
    nano \
    python3 \
    python3-pip \
    python3-dev \
    python3-matplotlib \
    unzip \
    pkg-config \
    libpq-dev \
    curl \
    build-essential \
    wget \
    openssh-client \
    graphviz-dev \
    openssl \
    libssl-dev \
    libffi6 \
    libffi-dev \
    libpng-dev \
    libhdf5-serial-dev \
    hdf5-tools \
    libhdf5-dev \
    zlib1g-dev \
    zip && \
    rm -rf /var/lib/apt/lists/*

ARG PROJECT=sova-tts-gpu
ARG PROJECT_DIR=/sova-tts
RUN mkdir -p $PROJECT_DIR
WORKDIR $PROJECT_DIR

COPY requirements.txt .
RUN pip3 install --upgrade pip
RUN pip3 install setuptools wheel cython
RUN pip3 install --ignore-installed PyYAML -r requirements.txt

RUN git clone https://github.com/sovaai/sova-tts-tps && cd sova-tts-tps && git checkout v1.1.1 && pip3 install .
RUN cd .. && rm -rf sova-tts-tps

RUN apt-get install -y locales && locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

CMD gunicorn --access-logfile - -w 1 --bind 0.0.0.0:8899 app:app --timeout 15000
```
docker-compose is also modified to support gpu:
```
version: '3.7'

services:
  sova-tts-gpu:
    restart: always
    container_name: sova-tts-gpu
    build:
      context: .
      dockerfile: Dockerfile.gpu
    image: sova-tts-gpu:master
    volumes:
      - .:/sova-tts
    ports:
      - 8899:8899
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
```

**Comment by Dekakhrone** [comment]
Hi @sskorol! I'm afraid we have not tested our service on jetson devices, so we do not have a ready-made recipe for solving this problem. Could you please add more logging messages so we can understand if it even comes down to loading the service?
