### ISSUE TITLE
Inference using GST?

### ISSUE THREAD

**Issue by yerzhan7orazayev** [sovaai/sova-tts#7]
Does your current code and models support style transfer using GST?

Thanks,
Yerzhan.

**Comment by Dekakhrone** [comment]
Hello again! As I answered you via email:

In the current version of SOVA TTS, this is impossible, because the "synthesize" method does not support passing the required arguments, but you can implement it yourself by adding a "token_idx" to the [request arguments](https://github.com/sovaai/sova-tts/blob/master/app.py#L31), which will then be passed to the [inference method](https://github.com/sovaai/sova-tts-engine/blob/master/model.py#L746) of the tacotron.

**Comment by yerzhan7orazayev** [comment]
RuntimeError: Error(s) in loading state_dict for Tacotron2:
	Missing key(s) in state_dict: "gst.encoder.convs.0.block.0.conv.weight", "gst.encoder.convs.0.block.0.conv.bias", "gst.encoder.convs.0.block.1.weight", "gst.encoder.convs.0.block.1.bias", "gst.encoder.convs.0.block.1.running_mean", "gst.encoder.convs.0.block.1.running_var", "gst.encoder.convs.1.block.0.conv.weight", "gst.encoder.convs.1.block.0.conv.bias", "gst.encoder.convs.1.block.1.weight", "gst.encoder.convs.1.block.1.bias", "gst.encoder.convs.1.block.1.running_mean", "gst.encoder.convs.1.block.1.running_var", "gst.encoder.convs.2.block.0.conv.weight", "gst.encoder.convs.2.block.0.conv.bias", "gst.encoder.convs.2.block.1.weight", "gst.encoder.convs.2.block.1.bias", "gst.encoder.convs.2.block.1.running_mean", "gst.encoder.convs.2.block.1.running_var", "gst.encoder.convs.3.block.0.conv.weight", "gst.encoder.convs.3.block.0.conv.bias", "gst.encoder.convs.3.block.1.weight", "gst.encoder.convs.3.block.1.bias", "gst.encoder.convs.3.block.1.running_mean", "gst.encoder.convs.3.block.1.running_var", "gst.encoder.convs.4.block.0.conv.weight", "gst.encoder.convs.4.block.0.conv.bias", "gst.encoder.convs.4.block.1.weight", "gst.encoder.convs.4.block.1.bias", "gst.encoder.convs.4.block.1.running_mean", "gst.encoder.convs.4.block.1.running_var", "gst.encoder.convs.5.block.0.conv.weight", "gst.encoder.convs.5.block.0.conv.bias", "gst.encoder.convs.5.block.1.weight", "gst.encoder.convs.5.block.1.bias", "gst.encoder.convs.5.block.1.running_mean", "gst.encoder.convs.5.block.1.running_var", "gst.encoder.gru.weight_ih_l0", "gst.encoder.gru.weight_hh_l0", "gst.encoder.gru.bias_ih_l0", "gst.encoder.gru.bias_hh_l0", "gst.stl.embed", "gst.stl.attention.W_query.linear_layer.weight", "gst.stl.attention.W_key.linear_layer.weight", "gst.stl.attention.W_value.linear_layer.weight". 



I am getting the following error while I am trying to use GST at inference. Supposedly. your checkpoints does not contain GST weights yet. Could you please update them?

Thanks,
Yerzhan.
